title: sophiarose
description: A website about music typography
footer_text: Copyright 2021 Sophia Lawrence Hawkins
header_feature_image: ../uploads/placeholder4.jpg
header_text: Music Typography
header_text_color: "#000000"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
